Feature/OMO-99/요청 함수 구현
depromeet/omo-frontend pull request #38
Opened 2021-11-09 08:05 UTC by jonghopark95

## :bookmark_tabs: 제목

### 요청 함수 구현

## :heavy_check_mark: 셀프 체크리스트

> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [x] Warning Message가 발생하지 않았나요?
- [x] Coding Convention을 준수했나요?

## :speech_balloon: 작업 내용

> 구현 내용 및 작업 했던 내역

- [x] Axios instance, 요청 함수 구현
- [x] /home으로 들어올 경우 access는 axios에, refresh 는 local storage에 셋팅

## :construction: PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 요청 함수들을 러프하게 작성했습니다. 보시고 맘에 안드시면 리뷰 부탁드립니다!!

2021-11-09 12:28 UTC, KangyeolLee requested changes
수고하셔씀당~
몇 가지 체인지만 제안드려요!

2021-11-09 12:28 UTC, KangyeolLee commented on src/pages/home.tsx
> +      setStorageItem(tokenInfo.refresh);
access 토큰은 헤더에
refresh 토큰은 로컬스토리지에 보관하는 구조인가요?

2021-11-09 12:28 UTC, KangyeolLee commented on src/request/index.ts
> +  instance.defaults.headers.common['Authorization'] = token;
```suggestion
  instance.defaults.headers.common['Authorization'] = `Bearer ${token}`;
```
저희 명세에 따르면 `Bearer token`이라 `Bearer` 추가되어야 할 거 같슴둥

2021-11-09 12:28 UTC, KangyeolLee commented on src/request/index.ts
> +  instance.get(`/omakases?level=${param.level}&keyword=${param.keyword}`);
`keyword`는 없을 수도 있어서 optional로 처리되어야 할 거 같슴당

2021-11-10 02:54 UTC, jonghopark95 commented on src/pages/home.tsx
> +      setStorageItem(tokenInfo.refresh);
refresh token은 secure 속성과 함께 쿠키에 넣도록 수정했습니다

2021-11-10 02:59 UTC, jonghopark95 commented on src/request/index.ts
> +  instance.defaults.headers.common['Authorization'] = token;
추가했습니다 감사합니다~

2021-11-10 02:59 UTC, jonghopark95 commented on src/request/index.ts
> +  instance.get(`/omakases?level=${param.level}&keyword=${param.keyword}`);
헐 맞네요 수정하겠습니다

2021-11-10 04:46 UTC, KangyeolLee commented on src/pages/home.tsx
> +      setStorageItem(tokenInfo.refresh);
우리지금 secure 속성 넣으면 못 가져 올거 같은데 배포 서버가 지금 http로 띄워져 있어서 ssl 통신이 안 되지 않나유

2021-11-10 04:51 UTC, jonghopark95 commented on src/pages/home.tsx
> +      setStorageItem(tokenInfo.refresh);
맞네요맞네요 아무 생각없이 넣었네요... secure 속성 빼겠습니다 
근데 지금 보니 저희 refresh token으로 access token 받아오는 API 가 없네요...?

2021-11-10 05:25 UTC, hy57in commented
그럼 api mocking 필요 없이 src/request에 있는 요청함수들을 각 페이지에 import해서 사용하는 것을 구현하면 되나요?

2021-11-10 05:36 UTC, hy57in approved these changes
엄청 깔끔하네요!!! 수고하셨습니다!!!!!

2021-11-10 08:13 UTC, KangyeolLee commented on src/pages/home.tsx
> +      setStorageItem(tokenInfo.refresh);
어 토큰은 근데 그냥 물어본건데 굳이 쿠키로 안 바꾸셔두 돼요 ㅋㅋ

2021-11-10 08:50 UTC, jonghopark95 commented on src/pages/home.tsx
> +      setStorageItem(tokenInfo.refresh);
ㅋㅋㅋㅋㅋ 사실 당장 refresh 쓸일이 없을것 같아서 나중에 의논하고 처리해도 될듯 하네요 :) 일단 저대로 놔둘게요!!

2021-11-11 14:47 UTC, KangyeolLee approved these changes

2021-11-11 15:41 UTC, merged