feature: omo-105/랭커가 다녀간 오마카세 BottomSheet 마크업, api 연동
depromeet/omo-frontend pull request #46
Opened 2021-11-24 19:41 UTC by hy57in

## :bookmark_tabs: 제목
<img src="https://user-images.githubusercontent.com/60775453/143279296-8bd3e043-a892-434d-9f61-47500ecb1af1.png" width="30%" />
이런 오류 뜨는 상태.. 랭커 목록 api에서 profile_url가 수정되야할 것 같습니당

- 랭커가 다녀간 오마카세 BottomSheet 마크업, api 연동
## :heavy_check_mark: 셀프 체크리스트

> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [ ] Warning Message가 발생하지 않았나요?
- [ ] Coding Convention을 준수했나요?

## :speech_balloon: 작업 내용

> 구현 내용 및 작업 했던 내역

- [x] 랭커가 다녀간 오마카세 BottomSheet 마크업
- [x] (작업 내역 2)
- [x] (작업 내역 3)

## :construction: PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- BottomSheet를 빠르게 구현하기 위해 라이브러리를 사용했습니다.[링크](https://www.npmjs.com/package/actionsheet-react)
- (특이 사항 2)
- (특이 사항 3)

2021-11-30 14:35 UTC, KangyeolLee requested changes
리뷰가 늦었네용 죄송죄송

2021-11-30 14:35 UTC, KangyeolLee commented on next.config.js
> +    domains: ['c2.poing.co.kr', '101.101.209.153'],
훔훔 이거 public IP는 가리는게 좋을거 같아유

2021-12-10 13:42 UTC, KangyeolLee commented on next.config.js
> +    domains: ['c2.poing.co.kr', '101.101.209.153'],
이젠`server.woowa.link` 쪽으로 변경하면 될거에요

2021-12-11 07:48 UTC, hy57in commented on next.config.js
> +    domains: ['c2.poing.co.kr', '101.101.209.153'],
이건 종호님이 반영해주셧음니다

2021-12-16 13:58 UTC, jonghopark95 approved these changes

2021-12-16 13:59 UTC, KangyeolLee approved these changes

2021-12-16 14:00 UTC, merged